#简体中文：zh-CN
#English: en-US
Language: en-US

#Oxygen system enabled world, manual modification is not recommended
Worlds: []
CaveNonOxygenWorlds: []

#Oxygen holding capacity of each grade of oxygen mask, unit: second
#Of these, the first is the time without an oxygen mask
OxygenMask: [20, 600, 1200, 1800]
#The amount of oxygen that an oxygen tank can recover, unit: second
OxygenTank: 300
#The amount of oxygen recovered in hermetic cabin for one second, unit: second/s
RoomOxygenAdd: 5
#The amount of oxygen recovered by a click of an oxygen station, unit: second
OxygenStationOxygenAdd: 60
#The amount of oxygen consume when player hurt others, unit: second
OxygenReducedOnDamagedOthers: 0.5
#The amount of oxygen consume when player running,unit: second/s
OxygenReducedOnRunning: 0.2
#The amount of oxygen consume when player jump, unit: second
OxygenReducedOnJumping: 1.0

#The size of cave detection area, unit: block
#If there are many players online,consider decreasing this value
CaveCheckSize: 11
#Y shift when detecting cave
CaveCheckYShift: 1
#The proportion of "cavity blocks" needed to determine as a cave
CaveP: 0.5
#AS FOR 1.16 OR HIGH YOU CAN ADD
# - "CRIMSON_NYLIUM","WARPED_NYLIUM","NETHER_GOLD_ORE","ANCIENT_DEBRIS"
#AS FOR 1.17 OR HIGH YOU CAN ADD
#  - "DEEPSLATE" "COBBLED_DEEPLATE" "CALCITE" "TUFF","DIRPSTONE_BLOCK"
#  - "ROOTED_DIRT","DEEPSLATE_COAL_ORE","DEEPSLATE_IROON_ORE","DEEPSLATE_COPPER_ORE"
#  - "DEEPSLATE_GOLD_ORE","DEEPSLATE_REDSTONE_ORE","DEEPSLATE_EMERALD_ORE"
#  - "LAPIS_ORE","DEEPSLATE_DIAMOND_ORE"
CaveBlockList: ["STONE", "GRANITE","DIORITE","ANDESITE","DIRT", "SAND","GRAVEL","COBBLESTONE","COAL_ORE","IRON_ORE","GOLD_ORE","REDSTONE_ORE","EMERALD_ORE","LAPIS_ORE","DIAMOND_ORE","NETHER_QUARTZ_ORE","SANDSTONE"]


#Sound
#Whether to play the machine startup sound
PlayMachineStartUpSound: true
#Whether to play gas flow sound when entering/exiting a hermetic cabin
PlayEnterRoomSound: true
#Whether to play a sound when a hermetic cabin is broken
PlayAirLockBreakSound: true
#Whether to play a sound when upgrading an item
PlayItemUpgradeSound: true
#Whether to play a sound when the oxygen tank is used
PlayOxygenTankUseSound: true
#Whether to play a sound when infusing oxygen at the oxygen station
PlayRefillOxygenSound: true

#Whether to enable the built-in synthesis table of this plugin
#If you need a higher degree of customization, consider using the other Table plugin, use /oxygen get to get all items
EnableIngredient: true
# ABCDEFGHI -> ABC
#              DEF
#              GHI
#Item name can be found here：https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
#Oxygen system Upgrader T1
OxygenMaskT1Ingredient: ["COAL","COAL","COAL","COAL","IRON_INGOT","COAL","COAL","COAL","COAL"]
#Oxygen system Upgrader T2
OxygenMaskT2Ingredient: ["AIR","DIAMOND","AIR","DIAMOND","GOLD_INGOT","DIAMOND","AIR","DIAMOND","AIR"]
#Oxygen system Upgrader T3
OxygenMaskT3Ingredient: ["AIR","DIAMOND","AIR","DIAMOND","NETHER_STAR","DIAMOND","AIR","DIAMOND","AIR"]
#Oxygen Generator
OxygenGeneratorIngredient: ['IRON_INGOT','GOLD_INGOT','IRON_INGOT','DIAMOND','SMOKER','DIAMOND','IRON_INGOT','GOLD_INGOT','IRON_INGOT']
#Oxygen Station
OxygenStationIngredient: ['IRON_INGOT','GOLD_INGOT','IRON_INGOT','GOLD_INGOT','LOOM','GOLD_INGOT','IRON_INGOT','GOLD_INGOT','IRON_INGOT']
#Start Stone
BootStoneIngredient: ['AIR','AIR','AIR','AIR','FLINT_AND_STEEL','IRON_INGOT','AIR','IRON_INGOT','AIR']
#Oxygen Tank (Empty)
OxygenTankProembryoIngredient: ['AIR','IRON_INGOT','AIR','IRON_INGOT','SLIME_BALL','IRON_INGOT','AIR','IRON_INGOT','AIR']


#Debug mode
#In Debug mode, when creating a new airlock or destroying an airlock,
#the blocks that are considered to be the walls of the airlock will be replaced with stained-glass blocks for easy viewing.
Debug: false